# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
                ('extension', models.CharField(max_length=10)),
                ('dateOfModification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('departmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserToDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('doc', models.ManyToManyField(to='Documents.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.User')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='documents',
            field=models.ManyToManyField(to='Documents.Document'),
        ),
    ]
