# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:58
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/sasha/PycharmProjects/DocServer/files/doc'), upload_to='')),
                ('extension', models.CharField(max_length=10)),
                ('dateOfModification', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='documents',
            field=models.ManyToManyField(to='Documents.Document'),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(to='Documents.User'),
        ),
    ]
