# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodoc',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='usertodoc',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserToDoc',
        ),
    ]
