# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20171117_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('doc', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
